baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'hermit-v2'


title = 'Tijolo Tech'
[params]
    homeSubtitle = "Construindo o futuro da sua empresa com você"
    homeSubtitlePrinter = true


[menu]
    [[menu.main]]
        name = "Contate-nos"
        url = "contact-me/"
        weight = 20
